In [1]:
import csv
with open('dataset.csv') as file:
  data = list(csv.reader(file))
print(len(data))
data[:5]

199


[['0', '0.0', '2', '0', '1', '1.0', '2', '3', '3', '2.67', '1.67'],
 ['1', '0.0', '4', '0', '4', '2.67', '3', '2', '2', '2.33', '-0.33'],
 ['2', '0.0', '3', '0', '2', '1.67', '4', '4', '4', '4.0', '2.33'],
 ['3', '0.0', '2', '0', '2', '1.33', '5', '4', '5', '4.67', '3.33'],
 ['4', '0.0', '3', '1', '3', '2.33', '4', '4', '5', '4.33', '2.0']]

In [2]:
data[2][0]

'2'

In [3]:
import numpy as np
np.array(data)

array([['0', '0.0', '2', ..., '3', '2.67', '1.67'],
       ['1', '0.0', '4', ..., '2', '2.33', '-0.33'],
       ['2', '0.0', '3', ..., '4', '4.0', '2.33'],
       ...,
       ['196', '2.0', '', ..., '', '', ''],
       ['197', '2.0', '', ..., '', '', ''],
       ['198', '2.0', '', ..., '', '', '']], shape=(199, 11), dtype='<U5')

In [4]:
array = np.genfromtxt('dataset.csv', delimiter=',')
array

array([[  0.  ,   0.  ,   2.  , ...,   3.  ,   2.67,   1.67],
       [  1.  ,   0.  ,   4.  , ...,   2.  ,   2.33,  -0.33],
       [  2.  ,   0.  ,   3.  , ...,   4.  ,   4.  ,   2.33],
       ...,
       [196.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [197.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [198.  ,   2.  ,    nan, ...,    nan,    nan,    nan]],
      shape=(199, 11))

## Indexing and slicing

In [5]:
array[2, 0]

np.float64(2.0)

In [6]:
array[2][0]

np.float64(2.0)

In [7]:
# Returns the second column:
array[:, 1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [8]:
# Returns the second row:
array[1, :]

array([ 1.  ,  0.  ,  4.  ,  0.  ,  4.  ,  2.67,  3.  ,  2.  ,  2.  ,
        2.33, -0.33])

In [9]:
# This also returns the second row:
array[1]

array([ 1.  ,  0.  ,  4.  ,  0.  ,  4.  ,  2.67,  3.  ,  2.  ,  2.  ,
        2.33, -0.33])

In [10]:
# Returns columns from index 2 to 5 in the second row
array[1, 2:6]

array([4.  , 0.  , 4.  , 2.67])

In [11]:
# First two columns of some rows:
array[1:5, :2]

array([[1., 0.],
       [2., 0.],
       [3., 0.],
       [4., 0.]])

In [12]:
# Slicing with strides (aka steps)
# Get the second column of every 20 rows:
array[::20, 1]

array([0., 0., 1., 1., 1., 1., 1., 2., 2., 2.])

In [13]:
# Strides can be used in every dimension:
print(array.shape)
array[::5, ::2].shape

(199, 11)


(40, 6)

In [14]:
array[:100, :100].shape

(100, 11)

In [15]:
array[:100, :100].reshape(5, 5, 4, 11)

array([[[[ 0.  ,  0.  ,  2.  , ...,  3.  ,  2.67,  1.67],
         [ 1.  ,  0.  ,  4.  , ...,  2.  ,  2.33, -0.33],
         [ 2.  ,  0.  ,  3.  , ...,  4.  ,  4.  ,  2.33],
         [ 3.  ,  0.  ,  2.  , ...,  5.  ,  4.67,  3.33]],

        [[ 4.  ,  0.  ,  3.  , ...,  5.  ,  4.33,  2.  ],
         [ 5.  ,  0.  ,  2.  , ...,  4.  ,  4.  ,  2.67],
         [ 6.  ,  0.  ,  3.  , ...,  2.  ,  2.33,  0.  ],
         [ 7.  ,  0.  ,  4.  , ...,  3.  ,  3.33,  1.67]],

        [[ 8.  ,  0.  ,  2.  , ...,  3.  ,  3.  ,  1.67],
         [ 9.  ,  0.  ,  3.  , ...,  5.  ,  4.  ,  2.  ],
         [10.  ,  0.  ,  3.  , ...,  5.  ,  4.33,  3.  ],
         [11.  ,  0.  ,  2.  , ...,  2.  ,  2.67,  1.67]],

        [[12.  ,  0.  ,  3.  , ...,  4.  ,  3.33,  1.67],
         [13.  ,  0.  ,  2.  , ...,  3.  ,  2.  ,  0.67],
         [14.  ,  0.  ,  1.  , ...,  2.  ,  2.33,  1.33],
         [15.  ,  0.  ,  3.  , ...,  5.  ,  4.67,  3.33]],

        [[16.  ,  0.  ,  4.  , ...,  5.  ,  4.67,  3.  ],
      

In [16]:
# We can index using tuples:
array[(1,2)] == array[1, 2]

np.True_

In [17]:
# We can index rows (and columns) using numpy arrays:
array[np.array([3, 4])]

array([[3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33],
       [4.  , 0.  , 3.  , 1.  , 3.  , 2.33, 4.  , 4.  , 5.  , 4.33, 2.  ]])

## Boolean masks

In [18]:
array[np.array([2, 3])] == np.array([array[2], array[3]])

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True]])

In [19]:
small_array = array[:3, :3].astype(float)
small_array

array([[0., 0., 2.],
       [1., 0., 4.],
       [2., 0., 3.]])

In [20]:
index = np.where(small_array > 2)
index

(array([1, 2]), array([2, 2]))

In [21]:
small_array[index]

array([4., 3.])

In [22]:
small_array[small_array > 2]

array([4., 3.])

In [23]:
small_array

array([[0., 0., 2.],
       [1., 0., 4.],
       [2., 0., 3.]])

In [24]:
np.delete(small_array, index)

array([0., 1., 0., 4., 2., 0., 3.])

In [25]:
# Index carries a tupple of lists:
np.delete(small_array, ([1,2],[2,2]))

array([0., 1., 0., 4., 2., 0., 3.])

In [26]:
# It looks like the object (tupple of lists) is flattened and used as a set of indexes to delete:
np.delete(small_array, [1, 2])

array([0., 1., 0., 4., 2., 0., 3.])

In [27]:
small_array > 2

array([[False, False, False],
       [False, False,  True],
       [False, False,  True]])

In [28]:
small_array[small_array > 2]

array([4., 3.])

In [29]:
small_array[(small_array > 0) & (small_array < 4)]

array([2., 1., 2., 3.])

In [30]:
np.isnan(array).any()

np.True_

In [31]:
array[np.isnan(array)] = 0
np.isnan(array).any()

np.False_

In [32]:
new_array = np.arange(50).reshape(5, 10)
new_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [33]:
mask = (new_array > 15) & (new_array < 35)
mask

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [34]:
mask[:, 5]

array([False, False,  True, False, False])

In [35]:
new_array[mask[:, 5], 2:8:2]

array([[22, 24, 26]])

## Broadcasting

In [36]:
a = np.arange(4)
b = np.arange(20).reshape(4, 5)
try:
  a * b
except Exception as e:
  print(e)

operands could not be broadcast together with shapes (4,) (4,5) 


In [37]:
a.reshape(4, 1) + b

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [38]:
a = np.arange(10, 51, 10).reshape(5, 1)
a

array([[10],
       [20],
       [30],
       [40],
       [50]])

In [39]:
b = np.arange(3).reshape(1, 3)
b

array([[0, 1, 2]])

In [40]:
a + b

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

## Operations

In [41]:
array = np.genfromtxt('dataset.csv', delimiter=',')
array

array([[  0.  ,   0.  ,   2.  , ...,   3.  ,   2.67,   1.67],
       [  1.  ,   0.  ,   4.  , ...,   2.  ,   2.33,  -0.33],
       [  2.  ,   0.  ,   3.  , ...,   4.  ,   4.  ,   2.33],
       ...,
       [196.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [197.  ,   2.  ,    nan, ...,    nan,    nan,    nan],
       [198.  ,   2.  ,    nan, ...,    nan,    nan,    nan]],
      shape=(199, 11))

In [42]:
# Select rows that have no NAN values only:
clean_array = array[~np.isnan(array).any(axis=1), :]
clean_array

array([[  0.  ,   0.  ,   2.  , ...,   3.  ,   2.67,   1.67],
       [  1.  ,   0.  ,   4.  , ...,   2.  ,   2.33,  -0.33],
       [  2.  ,   0.  ,   3.  , ...,   4.  ,   4.  ,   2.33],
       ...,
       [178.  ,   2.  ,   4.  , ...,   1.  ,   2.  ,   0.  ],
       [179.  ,   2.  ,   4.  , ...,   1.  ,   1.33,  -1.  ],
       [180.  ,   2.  ,   1.  , ...,   2.  ,   2.67,   0.67]],
      shape=(151, 11))

In [43]:
# Sum all the elements:
clean_array.sum()

np.float64(16658.97)

In [44]:
# Sum along rows, vertically, results count equals column count
clean_array.sum(axis=0)

array([13215.  ,   174.  ,   478.  ,   203.  ,   294.  ,   324.99,
         441.  ,   491.  ,   445.  ,   458.98,   134.  ])

In [45]:
# Sum along columns, horizontally, results count equals row count
clean_array.sum(axis=1)

array([ 16.34,  20.67,  27.  ,  30.33,  32.66,  29.  ,  24.66,  28.67,
        27.  ,  35.  ,  35.66,  27.34,  33.67,  27.  ,  28.66,  42.33,
        44.34,  35.  ,  43.33,  41.66,  46.  ,  50.  ,  46.34,  45.66,
        42.34,  55.33,  48.  ,  45.  ,  57.66,  53.  ,  60.67,  55.34,
        65.34,  61.  ,  59.34,  57.67,  63.  ,  59.67,  68.  ,  61.67,
        60.  ,  81.34,  71.33,  71.  ,  76.66,  68.  ,  75.  ,  71.66,
        87.66,  70.  ,  73.66,  79.66,  76.34,  74.  ,  88.  ,  83.66,
        86.67,  89.66,  86.  ,  89.67,  96.66,  86.67,  89.  ,  94.66,
        89.34,  89.66,  95.66,  95.66,  94.33, 101.34,  96.33, 109.  ,
        95.66, 100.  ,  98.34, 103.34, 110.  , 109.66, 105.  , 100.  ,
       110.34, 107.33, 106.34, 109.  , 106.  , 111.33, 110.66, 107.34,
       111.66, 119.  , 119.  , 117.  , 115.66, 124.33, 123.66, 123.  ,
       118.67, 125.  , 123.67, 118.34, 151.67, 152.34, 154.  , 159.34,
       157.67, 162.33, 156.34, 157.66, 162.66, 162.34, 166.34, 166.  ,
      

In [46]:
np.std(clean_array[:, 8])

np.float64(1.126373066250029)

In [47]:
# Matrix multiplication:
A = np.arange(12).reshape(4,3)
B = np.arange(15).reshape(3,5)
A.dot(B)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118],
       [115, 136, 157, 178, 199],
       [160, 190, 220, 250, 280]])

In [48]:
# Another notation for matrix multiplication:
A @ B

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118],
       [115, 136, 157, 178, 199],
       [160, 190, 220, 250, 280]])

## Sorting

In [49]:
a = array[3]
a

array([3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33])

In [50]:
# Create a sorted copy of an array:
np.sort(a)

array([0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 3.33, 4.  , 4.67, 5.  , 5.  ])

In [51]:
a

array([3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33])

In [52]:
# Sort the original array:
a.sort()
a

array([0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 3.33, 4.  , 4.67, 5.  , 5.  ])

In [56]:
# And because a is a slice of array, it also gets sorted:
array[3]

array([0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 3.33, 4.  , 4.67, 5.  , 5.  ])

In [57]:
array = np.genfromtxt('dataset.csv', delimiter=',')
b = array[1:4, :10]
b

array([[1.  , 0.  , 4.  , 0.  , 4.  , 2.67, 3.  , 2.  , 2.  , 2.33],
       [2.  , 0.  , 3.  , 0.  , 2.  , 1.67, 4.  , 4.  , 4.  , 4.  ],
       [3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67]])

In [59]:
np.sort(b)

array([[0.  , 0.  , 1.  , 2.  , 2.  , 2.33, 2.67, 3.  , 4.  , 4.  ],
       [0.  , 0.  , 1.67, 2.  , 2.  , 3.  , 4.  , 4.  , 4.  , 4.  ],
       [0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 4.  , 4.67, 5.  , 5.  ]])

In [60]:
np.sort(b, axis=-1)

array([[0.  , 0.  , 1.  , 2.  , 2.  , 2.33, 2.67, 3.  , 4.  , 4.  ],
       [0.  , 0.  , 1.67, 2.  , 2.  , 3.  , 4.  , 4.  , 4.  , 4.  ],
       [0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 4.  , 4.67, 5.  , 5.  ]])

In [62]:
np.sort(b, axis=1)

array([[0.  , 0.  , 1.  , 2.  , 2.  , 2.33, 2.67, 3.  , 4.  , 4.  ],
       [0.  , 0.  , 1.67, 2.  , 2.  , 3.  , 4.  , 4.  , 4.  , 4.  ],
       [0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 4.  , 4.67, 5.  , 5.  ]])

In [63]:
np.sort(b, axis=0)

array([[1.  , 0.  , 2.  , 0.  , 2.  , 1.33, 3.  , 2.  , 2.  , 2.33],
       [2.  , 0.  , 3.  , 0.  , 2.  , 1.67, 4.  , 4.  , 4.  , 4.  ],
       [3.  , 0.  , 4.  , 0.  , 4.  , 2.67, 5.  , 4.  , 5.  , 4.67]])

In [68]:
a = array[3]
a

array([3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33])

In [69]:
np.argsort(a)

array([ 1,  3,  5,  2,  4,  0, 10,  7,  9,  6,  8])

In [70]:
a[np.argsort(a)]

array([0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 3.33, 4.  , 4.67, 5.  , 5.  ])

In [72]:
np.sort(a)

array([0.  , 0.  , 1.33, 2.  , 2.  , 3.  , 3.33, 4.  , 4.67, 5.  , 5.  ])

## Searching

In [77]:
a = array[1]
a

array([ 1.  ,  0.  ,  4.  ,  0.  ,  4.  ,  2.67,  3.  ,  2.  ,  2.  ,
        2.33, -0.33])

In [78]:
np.where(a == 4)

(array([2, 4]),)

In [79]:
a[np.where(a == 4)]

array([4., 4.])

In [80]:
a = array[2:5]
a

array([[2.  , 0.  , 3.  , 0.  , 2.  , 1.67, 4.  , 4.  , 4.  , 4.  , 2.33],
       [3.  , 0.  , 2.  , 0.  , 2.  , 1.33, 5.  , 4.  , 5.  , 4.67, 3.33],
       [4.  , 0.  , 3.  , 1.  , 3.  , 2.33, 4.  , 4.  , 5.  , 4.33, 2.  ]])

In [91]:
# Finds the indexes of the elements that are less than 4,
# and returns the result as a touple of two arrays,
# the first one contains row indexes and the second one column indexes:
np.where(a < 4)

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]),
 array([ 0,  1,  2,  3,  4,  5, 10,  0,  1,  2,  3,  4,  5, 10,  1,  2,  3,
         4,  5, 10]))

In [95]:
np.where(a < 4, a, -100)

array([[   2.  ,    0.  ,    3.  ,    0.  ,    2.  ,    1.67, -100.  ,
        -100.  , -100.  , -100.  ,    2.33],
       [   3.  ,    0.  ,    2.  ,    0.  ,    2.  ,    1.33, -100.  ,
        -100.  , -100.  , -100.  ,    3.33],
       [-100.  ,    0.  ,    3.  ,    1.  ,    3.  ,    2.33, -100.  ,
        -100.  , -100.  , -100.  ,    2.  ]])

In [97]:
a = array[4]
a

array([4.  , 0.  , 3.  , 1.  , 3.  , 2.33, 4.  , 4.  , 5.  , 4.33, 2.  ])

In [99]:
def lessThan4(x):
  return x < 4
np.where(lessThan4(a))

(array([ 1,  2,  3,  4,  5, 10]),)

In [100]:
np.where(a < 4)

(array([ 1,  2,  3,  4,  5, 10]),)

In [104]:
# Find max value without sorting:
a[np.argmax(a)]

np.float64(5.0)

## Byte swapping

In [150]:
a = np.array([1, 256, 8755])
list(map(hex, a))

['0x1', '0x100', '0x2233']

In [151]:
def toBytes(x):
  bits = f'{x:0{64}b}'
  return ' '.join([bits[i:i+8] for i in range(0, len(bits), 8)])

list(map(toBytes, a))

['00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000001',
 '00000000 00000000 00000000 00000000 00000000 00000000 00000001 00000000',
 '00000000 00000000 00000000 00000000 00000000 00000000 00100010 00110011']

In [152]:
list(map(toBytes, a.byteswap()))

['00000001 00000000 00000000 00000000 00000000 00000000 00000000 00000000',
 '00000000 00000001 00000000 00000000 00000000 00000000 00000000 00000000',
 '00110011 00100010 00000000 00000000 00000000 00000000 00000000 00000000']

In [153]:
list(map(hex, a.byteswap()))

['0x100000000000000', '0x1000000000000', '0x3322000000000000']

In [154]:
a.byteswap()

array([  72057594037927936,     281474976710656, 3684507445142487040])