In [1]:
import numpy as np

## Creating arrays

In [2]:
np.array([
  [1, 2, 3],
  [4, 5, 6]
])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.array([
  [
    [1, 2],
    [3, 4]
  ],
  [
    [5, 6],
    [7, 8]
  ]
])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [4]:
np.array([-2, -1, 0, 1, 2], dtype=np.short)

array([-2, -1,  0,  1,  2], dtype=int16)

In [5]:
# Cast overflow is not allowed on creation:
try:
  np.array([-2, -1, 0, 1, 2], dtype=np.ushort)
except Exception as e:
  print(e)

Python integer -2 out of bounds for uint16


In [6]:
# Use astype to allow cast overflow:
np.array([-2, -1, 0, 1, 2]).astype(np.ushort)

array([65534, 65535,     0,     1,     2], dtype=uint16)

## Generating arrays

In [7]:
np.arange(3)

array([0, 1, 2])

In [8]:
np.arange(1, 3)

array([1, 2])

In [9]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(-1, -4, -1)

array([-1, -2, -3])

In [11]:
np.arange(0.1, 0.3, 0.1, dtype=np.single)

array([0.1, 0.2], dtype=float32)

In [12]:
# Be aware that float point rounding could break the range
# and the end element might be included in the range: 
np.arange(0.1, 0.4, 0.1, dtype=np.single)

array([0.1, 0.2, 0.3, 0.4], dtype=float32)

In [13]:
# linspace is more reliable:
np.linspace(0.1, 0.3, 3)

array([0.1, 0.2, 0.3])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [16]:
diag_matrix = np.diag([1, 2, 3, 4])
diag_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
np.diag(diag_matrix)

array([1, 2, 3, 4])

In [18]:
np.zeros((5, 3), dtype=np.uint)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint64)

In [19]:
np.zeros((4, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [20]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((5, 3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [22]:
np.random.rand(2, 2)

array([[0.73469799, 0.10022115],
       [0.596636  , 0.52110549]])

## Indexing & slicing

In [23]:
array = np.array([1, 2, 3])
array[-1]

np.int64(3)

In [24]:
array = np.array([
  [11, 12, 13, 14],
  [21, 22, 23, 24],
  [31, 32, 33, 34]
])
array[0, 0]

np.int64(11)

In [25]:
array[2, -2]

np.int64(33)

In [26]:
second_row = array[1]
second_row

array([21, 22, 23, 24])

In [27]:
second_row[0] = 210
array

array([[ 11,  12,  13,  14],
       [210,  22,  23,  24],
       [ 31,  32,  33,  34]])

In [28]:
array = np.array([0, 1, 2, 3, 4, 5])
#[start:stop:step]
array[1:4:2]

array([1, 3])

In [29]:
array[1:4:1]

array([1, 2, 3])

In [30]:
array[1:4]

array([1, 2, 3])

In [31]:
array[5:1:-1]

array([5, 4, 3, 2])

In [32]:
array[2:-2]

array([2, 3])

In [33]:
array = np.array([
  [11, 12, 13, 14],
  [21, 22, 23, 24],
  [31, 32, 33, 34]
])
#[row-start:row-end:step, col-start:col-end:step]
array[0:2:1, 1:3:1]

array([[12, 13],
       [22, 23]])

In [34]:
array[0:2, 1:3]

array([[12, 13],
       [22, 23]])

In [35]:
array[1, 2]

np.int64(23)

In [36]:
array[[1, 2]]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [37]:
#[[rows], col]
array[[1, 2], 1]

array([22, 32])

In [38]:
# array[0, 1] & array[2, 3]
array[[0, 2], [1, 3]]

array([12, 34])

## Filtering

In [39]:
array = np.array([-1, 0, 1])
array[[True, False, True]]

array([-1,  1])

In [40]:
array[array >= 0]

array([0, 1])

In [41]:
first_ten = np.arange(10)
first_ten[first_ten % 2 == 0]

array([0, 2, 4, 6, 8])

In [42]:
array = np.array([
  [-1, 0, 1],
  [-2, -1, 0],
  [-3, -2, -1]
])
array[array < -1]

array([-2, -3, -2])

## Reshaping

In [43]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
np.arange(6).reshape(2, 1, -1)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [45]:
np.arange(6).reshape(2, 1, 3)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [46]:
np.arange(6).reshape(2, 1, 3).reshape(-1)

array([0, 1, 2, 3, 4, 5])

## Broadcasting

In [47]:
a_2x3 = np.array([
  [1, 2, 3],
  [4, 5, 6]
])
a_1x3 = np.array([2, 2, 2])

In [48]:
a_2x3 + a_1x3

array([[3, 4, 5],
       [6, 7, 8]])

In [50]:
a_2x3 + np.array([
  [2, 2, 2],
  [2, 2, 2]
])

array([[3, 4, 5],
       [6, 7, 8]])

In [49]:
a_2x3 * a_1x3

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [51]:
a_2x3 * np.array([
  [2, 2, 2],
  [2, 2, 2]
])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### Broadcasting rules

In [52]:
# Array shapes are lined up from left to right
# and their dimensions must either match or be equal to 1:
# 2x3
# 1x3
# ---
# 2x3
result = np.full((2, 3), 5) + np.full((1, 3), 1)
result.shape

(2, 3)

In [55]:
# 2x3x5
#   1x5
# -----
# 2x3x5
result = np.full((2, 3, 5), 5) + np.full((1, 5), 1)
result.shape

(2, 3, 5)

In [56]:
# Scalars always work:
result = np.full((2, 3, 5), 5) + 1
result.shape

(2, 3, 5)

In [58]:
# These shapes don't match:
# 2x3
# 3x2
try:
  np.full((2, 3), 5) + np.full((3, 2), 1)
except Exception as e:
  print(e)

operands could not be broadcast together with shapes (2,3) (3,2) 


## Iteration

In [67]:
array = np.arange(6).reshape(2, 3)
for row in array:
  for col in row:
    print(col)

0
1
2
3
4
5


In [87]:
# Iterate over rows first:
array = np.array([
  [1, 1, 1],
  [2, 2, 2]
])
for item in np.nditer(array):
  print(item)

1
1
1
2
2
2


In [79]:
# Iterate over columns first:
for item in np.nditer(array, order='F'):
  print(item)

1
2
1
2
1
2


In [88]:
try:
  for item in np.nditer(array):
    item[...] = 0
except Exception as e:
  print(e)
array

assignment destination is read-only


array([[1, 1, 1],
       [2, 2, 2]])

In [89]:
for item in np.nditer(array, op_flags=['readwrite']):
  item[...] = 0
array

array([[0, 0, 0],
       [0, 0, 0]])