## Creating Matrices
> matlib is pending deprecation: https://numpy.org/doc/stable/reference/module_structure.html

In [1]:
import numpy as np
np.matlib.zeros((3, 3), int)

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [2]:
np.matlib.ones((3, 3))

matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [3]:
np.matlib.empty((3, 3), str)

matrix([['', '', ''],
        ['', '', ''],
        ['', '', '']], dtype='<U0')

In [4]:
np.matlib.identity(3)

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [5]:
np.matlib.eye(3, 4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [6]:
np.matlib.eye(3, 4, 1)

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

## Manipulating Matrices

In [7]:
matrix0 = np.zeros((3, 3))
matrix1 = np.ones((3, 3))

np.hstack((matrix0, matrix1))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [8]:
np.vstack((matrix0, matrix1))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.hsplit(np.hstack((matrix0, matrix1)), 2)

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])]

In [10]:
np.vsplit(np.vstack((matrix0, matrix1)), 2)

[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])]

In [11]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.tile(matrix, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [13]:
np.repeat(matrix, 2, 1)

array([[0, 0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5, 5],
       [6, 6, 7, 7, 8, 8]])

In [14]:
np.insert(matrix, [1, 2], 999, axis=1)

array([[  0, 999,   1, 999,   2],
       [  3, 999,   4, 999,   5],
       [  6, 999,   7, 999,   8]])

In [15]:
np.insert(matrix, [1, 2], 999, axis=0)

array([[  0,   1,   2],
       [999, 999, 999],
       [  3,   4,   5],
       [999, 999, 999],
       [  6,   7,   8]])

In [16]:
np.delete(matrix, [1, 2], axis=1)

array([[0],
       [3],
       [6]])

In [17]:
np.delete(matrix, [1, 2], axis=0)

array([[0, 1, 2]])

## Arithmetic Operations

In [18]:
matrix + matrix1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
matrix - matrix1

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [20]:
matrix * matrix1 # Element-wise multiplication

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [21]:
matrix / matrix1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [22]:
# Matrix multiplication:
matrix_2x3 = np.ones((2, 3))
matrix_3x2 = np.ones((3, 2))

matrix_2x2 = matrix_2x3 @ matrix_3x2
matrix_2x2

array([[3., 3.],
       [3., 3.]])

## Linear Algebra

In [23]:
# Rank (count of independant rows or columns)
matrix = np.array([
  [2, 4, 6],
  [1, 3, 5],
  [2 + 1, 4 + 3, 6 + 5]
])
np.linalg.matrix_rank(matrix)

np.int64(2)

In [24]:
# Trace (sum of diagonal values)
np.linalg.trace(matrix)

np.int64(16)

In [25]:
# Determinant
# https://www.mathsisfun.com/algebra/matrix-determinant.html
np.linalg.det(np.array([
  [2, 4],
  [1, 3]
]))

np.float64(2.0)

In [26]:
# Eigenvectors and eigenvalues
# https://www.mathsisfun.com/algebra/eigenvalue.html
np.linalg.eig(np.array([
  [2, 0, 0],
  [0, 4, 5],
  [0, 4, 3]
]))

EigResult(eigenvalues=array([-1.,  8.,  2.]), eigenvectors=array([[ 0.        ,  0.        ,  1.        ],
       [ 0.70710678, -0.78086881,  0.        ],
       [-0.70710678, -0.62469505,  0.        ]]))

In [27]:
# Product of original matrix and 3rd eigenvector (Av)
np.array([
  [2, 0, 0],
  [0, 4, 5],
  [0, 4, 3]
]) @ np.array([1, 0, 0])

array([2, 0, 0])

In [28]:
# 3rd eigenvalue multiplied by 3rd eigenvector (λv)
# Notice that Av = λv
2 * np.array([1, 0, 0])

array([2, 0, 0])

## Linear Equations

In [29]:
# https://www.mathsisfun.com/algebra/systems-linear-equations-matrices.html
# AX = B
# X = A⁻¹B
A = np.array([
  [1,	1, 1],
  [0,	2, 5],
  [2,	5, -1]
])
B = np.array([6, -4, 27])
np.linalg.inv(A) @ B

array([ 5.,  3., -2.])

In [30]:
np.linalg.solve(A, B)

array([ 5.,  3., -2.])