In [1]:
import numpy as np

## Simple arrays

In [2]:
np.array((1, 2, 3, 4, 5))

array([1, 2, 3, 4, 5])

In [3]:
np.array([[10, 20, 30], [40, 50, 60]])

array([[10, 20, 30],
       [40, 50, 60]])

## Data types

In [4]:
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [5]:
np.array([[10, 20, 30], [40, 50, 60]], dtype=complex)

array([[10.+0.j, 20.+0.j, 30.+0.j],
       [40.+0.j, 50.+0.j, 60.+0.j]])

In [6]:
print(np.array(['Tom', 'Anna', 'Lilly']).dtype)

<U5


In [7]:
print(np.array(['2020-01-01', '2010-10-10', '2000-12-31'], dtype='M').dtype)

datetime64[D]


In [8]:
print(np.array([1, 2, 3]).dtype)

int64


## Type conversion

In [9]:
int_array = np.array([1, 2, 3, 4, 5])
int_array

array([1, 2, 3, 4, 5])

In [10]:
np.array(int_array, dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [11]:
np.float64(int_array)

array([1., 2., 3., 4., 5.])

In [12]:
int_array.astype(complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

## Attributes

In [13]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
array

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
array.shape

(3, 3)

In [15]:
array.ndim

2

In [16]:
array.size

9

In [17]:
array.itemsize

8

In [18]:
array.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Creation functions

In [19]:
np.empty([3, 2], dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [20]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
np.full([3, 3], 10, dtype=int)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [23]:
np.asarray([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [24]:
np.fromiter(iter([10, 20, 30, 40, 50]), dtype=float)

array([10., 20., 30., 40., 50.])

In [25]:
buffer_list = b'Hello World!'
np.frombuffer(buffer_list, dtype='S1')

array([b'H', b'e', b'l', b'l', b'o', b' ', b'W', b'o', b'r', b'l', b'd',
       b'!'], dtype='|S1')

In [26]:
np.arange(start=0, stop=10, step=2, dtype=int)

array([0, 2, 4, 6, 8])

In [27]:
# Array with 5 values evenly spaced between 0 and 100
np.linspace(start=0, stop=100, num=5, dtype=int)

array([  0,  25,  50,  75, 100])

In [28]:
# Array with 5 values that have base 2 where the exponents are evenly spaced between 0 and 10
np.logspace(start=0, stop=10, num=5, base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])